services:
  nest-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: greyfighter/prepre:nest-app-v2
    restart: unless-stopped
    # container_name: nest-backend-app
    ports:
      - '8080-8082:8080'
      # - '8080:8080' # Expose first replica
      # - '8081:8080' # Expose second replica
      # - '8082:8080' # Expose third replica
    deploy:
      mode: replicated
      replicas: 3
