services:
  nest-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: greyfighter/prepre:nest-app-v2
    # container_name: nest-backend-app
    deploy:
      replicas: 3
    ports:
      - '8888:8888' # Expose first replica
      - '8889:8888' # Expose second replica
      - '8890:8888' # Expose third replica
