name: Pipeline CI/CD Build,Test,Push,Deploy

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  DOCKER_IMAGE_FRONTEND: greyfighter/prepre:nest-app-v2 # Use your Docker Hub repo name
  DOCKER_IMAGE_TAG: v2

##############################################################
##############################################################
# APP Build Stage Start
##############################################################
##############################################################

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      ##############################################################
      # Install deps and build the app Stage Start
      ##############################################################

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'

      - name: Install PNPM Globally
        run: npm install -g pnpm

      - name: Install nestjs app deps before build
        run: pnpm install

      - name: Build nestjs app to check build status
        run: pnpm build

      - name: Login to docker_hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION="v2.29.7"  # Use the latest version as needed
          sudo curl -SL "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Check version to confirm installation

      - name: Build and push Docker images to docker_hub
        run: |
          # 1- ==> Build the docker image usign docker-compose
          docker-compose -f docker-compose.yml build

          # 2- ==> Bush the docker image usign docker-compose
          docker-compose -f docker-compose.yml push

      ##############################################################
      # Connect to the VPS Stage Start
      ##############################################################

      - name: Install sshpass on github container
        run: sudo apt-get install -y sshpass

      - name: Set up SSH directory and keys on github container
        run: |
          mkdir -p ~/.ssh
          # Save the private key with proper line breaks
          echo "${{ secrets.VPS_SSH_KEY }}" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Save the public key
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4/ggD+eWySay8W1q3cqi/aiddrHGPM0ZR1yLLixvDFpxc6Dq7HlFGQixBQ5KjC0JntNuSgnsi3X9tMW0vjfI4CxDHzXu5Ab9DHRMWXz5l4kYhOwlpKmJeyBu8Yk9ErEP7QUpz1E3L+9xSkV5dAZvzdcLjtgyXSjKB3GBdG9IbNlFiY9FsOF7FNXEKqXiORQDF0BFQJ39nZX9LYzRD7MUue05XiC85Skqr4nvVyePomRpWV85YUiYY/vw2aFHNiMGHm39YfrnOaq8ZgmYIo3eny2VmU8x3nyA09YVb4AzSK/PluAVnbCKBKPLjy1msP6FtC9PcLx0nPeL8xfpMN+K/7Prv/7dJkO1tyJEmzTDSoCREkLWmUTrqU42TjVkxfPbkQNSi5de1UrQaR6c2PyOURxQL8eY9xup3UOusoBIsxQps/VgNKTO8XcMZDSmyd1TXeAkHheqkRmoBdJCYmx4dv3HTuTRy3ft0AeVflNEIlM+bAlrVSjtLX5tUgNyuR60= mahmoud@mahmoud-Latitude-E5570" > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub

          # Add host key
          ssh-keyscan -H 49.13.174.222 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Debug - Check SSH Setup on github container
        run: |
          echo "SSH directory contents:"
          ls -la ~/.ssh
          echo "Testing key file existence:"
          test -f ~/.ssh/id_rsa && echo "Private key exists" || echo "Private key missing"
          test -f ~/.ssh/id_rsa.pub && echo "Public key exists" || echo "Public key missing"

      - name: Test SSH Connection to the VPS from the github container
        run: |
          # First attempt - using key with password prompt
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -v -i ~/.ssh/id_rsa admin@49.13.174.222 "echo 'Connection successful!' && whoami" || echo "First attempt failed with $?"

      - name: Copy Docker Compose files to temporary directory on VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" scp -i ~/.ssh/id_rsa docker-compose.yml admin@49.13.174.222:/tmp/

      - name: Move files to the final directory with sudo
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -i ~/.ssh/id_rsa admin@49.13.174.222 "sudo mv /tmp/docker-compose.yml /opt/projects/backend-nest/"

  ##############################################################
  #  VPS Stage Start  Deploy |  Check health
  ##############################################################
